# Generated by Django 4.1.3 on 2022-11-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="birth_date",
            new_name="date_birth",
        ),
    ]
