# Generated by Django 4.1.3 on 2022-11-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_rename_birth_date_student_date_birth"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collection",
            new_name="Location",
        ),
    ]
