# Generated by Django 4.1.3 on 2022-11-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_rename_collection_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(default="-"),
            preserve_default=False,
        ),
    ]
