# Generated by Django 4.1.3 on 2022-11-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_event_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="collection",
            new_name="location",
        ),
    ]
