# Generated by Django 4.1.3 on 2022-11-07 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_rename_collection_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="cannot be less than 1"
                    )
                ],
            ),
        ),
    ]
