# Generated by Django 4.1.3 on 2022-11-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_event_unit_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slug",
        ),
    ]
