# Generated by Django 4.1.3 on 2022-11-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_order_student_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
